import {
  ArrowRight,
  ArrowUp,
  ChevronLeft,
  ChevronRight,
  Download,
  File,
  GraduationCap,
  Home,
  Laptop,
  Mail,
  Menu,
  Moon,
  Send,
  Sun,
  TerminalSquare,
  X,
} from "lucide-react"

export const Icons = {
  logo: TerminalSquare,
  close: X,
  menu: Menu,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowUp: ArrowUp,
  arrowRight: ArrowRight,
  download: Download,
  mail: Mail,
  send: Send,
  graduationCap: GraduationCap,
  file: File,
  home: Home,
}
